print("Hi", "Suriya", "Balan")
print("Hi", "Suriya", "Balan")
print("-----------------------")
print("Hi", "Suriya", "Balan", end="")
print("Hi", "Suriya", "Balan")
print("-----------------------")
print("Hi", "Suriya", "Balan", end="\t")
print("Hi", "Suriya", "Balan")
print("-----------------------")
print("Hi", "Suriya", "Balan", sep="-", end="\t")
print("Hi", "Suriya", "Balan")
print("-----------------------")
